CREATE SCHEMA connector;
GO

CREATE TABLE IF NOT EXISTS connector.users (
    id SERIAL PRIMARY KEY,
    user_id VARCHAR(255) UNIQUE NOT NULL,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);
GO

CREATE TABLE IF NOT EXISTS connector.edges (
    id SERIAL PRIMARY KEY,
    edge_id VARCHAR(255) NOT NULL UNIQUE,
    source VARCHAR(255) NOT NULL UNIQUE,
    target VARCHAR(255) NOT NULL UNIQUE,
    note text NOT NULL UNIQUE,
    type VARCHAR(255) NOT NULL UNIQUE,
    user_id VARCHAR(255) NOT NULL UNIQUE,
)
GO

CREATE TABLE IF NOT EXISTS connector.nodes (
    id SERIAL PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    position_x DOUBLE PRECISION NOT NULL UNIQUE,
    position_y DOUBLE PRECISION NOT NULL UNIQUE,
    style_height DOUBLE PRECISION NOT NULL UNIQUE,
    style_width DOUBLE PRECISION NOT NULL UNIQUE,
    note text NOT NULL UNIQUE,
    label text NOT NULL UNIQUE,
    type VARCHAR(255) NOT NULL UNIQUE,
    user_id VARCHAR(255) NOT NULL UNIQUE,
)